# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 497bf89392e92b1d433623a52318c31d68f0b325cdca25be28fea6600ddeb4beaae3606f5aee52437b80eec0df39bfb65b1f567828cb9c33b33898264eaf3fed

test:
  secret_key_base: 3af99f15283566716caf1f85832877c684eea8346d21b47d217957fc7c6ba36fe07189c5028ea0d0f8b357e840c134299250477c3e1714b3c98e2b01678ba486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
